 mkdir obioma
 mkdir biocomputing && cd biocomputing
 wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna
 wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
 mv wildtype.fna ../obioma/
 rm wildtype.gbk.1
 cd ..
 cd obioma
 grep -n 'tatata' wildtype.fna
 grep -n 'tatata' wildtype.fna > mutantgene.txt
 129  echo my favorite gene is MTOR gene
 nano
 cat MTOR.fasta
 3216:agatactaataactctatatatgttgatgcatcagtatctttggctgccgttacttcgaa
 3267:agaagcaattgactaagtagtatataaaacggatacgttagtttatctagcttaccatca
 obioma_chukueggu@cloudshell:~/Home/obioma$ grep -n 'tatata' wildtype.fna > mutantgene.txt
 obioma_chukueggu@cloudshell:~/Home/obioma$ echo my favorite gene is MTOR gene
 my favorite gene is MTOR gene
 obioma_chukueggu@cloudshell:~/Home/obioma$ nano
 obioma_chukueggu@cloudshell:~/Home/obioma$ cat MTOR.fasta
 GCTCCCGGCTTAGAGGACAGCGGGGAAGGCGGGCGGTGGGGCAGGGGGCCTGAAGCGGCGGTACCGGTGC
 TGGCGGCGGCAGCTGAGGCCTTGGCCGAAGCCGCGCGAATATTAAAGGAAACTTCTCTCTAAAGAACCTC
AGGGCAAGATGCTTGGAACCGGACCTGCCGCCGCCACCACCGCTGCCACCACATCTAGCAATGTGAGCGT
  142  CCTGCAGCAGTTTGCCAGTGGCCTAAAGAGCCGGAATGAGGAAACCAGGGCCAAAGCCGCCAAGGAGCTC
  143  CAGCACTATGTCACCATGGAACTCCGAGAGATGAGTCAAGAGGAGTCTACTCGCTTCTATGACCAACTGA
  144  ACCATCACATTTTTGAATTGGTTTCCAGCTCAGATGCCAATGAGAGGAAAGGTGGCATCTTGGCCATAGC
  145  TAGCCTCATAGGAGTGGAAGGTGGGAATGCCACCCGAATTGGCAGATTTGCCAACTATCTTCGGAACCTC
  146  CTCCCCTCCAATGACCCAGTTGTCATGGAAATGGCATCCAAGGCCATTGGCCGTCTTGCCATGGCAGGGG
  147  ACACTTTTACCGCTGAGTACGTGGAATTTGAGGTGAAGCGAGCCCTGGAATGGCTGGGTGCTGACCGCAA
  148  TGAGGGCCGGAGACATGCAGCTGTCCTGGTTCTCCGTGAGCTGGCCATCAGCGTCCCTACCTTCTTCTTC
  149  CAGCAAGTGCAACCCTTCTTTGACAACATTTTTGTGGCCGTGTGGGACCCCAAACAGGCCATCCGTGAGG
  150  GAGCTGTAGCCGCCCTTCGTGCCTGTCTGATTCTCACAACCCAGCGTGAGCCGAAGGAGATGCAGAAGCC
  151  TCAGTGGTACAGGCACACATTTGAAGAAGCAGAGAAGGGATTTGATGAGACCTTGGCCAAAGAGAAGGGC
  152  ATGAATCGGGATGATCGGATCCATGGAGCCTTGTTGATCCTTAACGAGCTGGTCCGAATCAGCAGCATGG
  153  AGGGAGAGCGTCTGAGAGAAGAAATGGAAGAAATCACACAGCAGCAGCTGGTACACGACAAGTACTGCAA
  154  AGATCTCATGGGCTTCGGAACAAAACCTCGTCACATTACCCCCTTCACCAGTTTCCAGGCTGTACAGCCC
  155  CAGCAGTCAAATGCCTTGGTGGGGCTGCTGGGGTACAGCTCTCACCAAGGCCTCATGGGATTTGGGACCT
  156  CCCCCAGTCCAGCTAAGTCCACCCTGGTGGAGAGCCGGTGTTGCAGAGACTTGATGGAGGAGAAATTTGA
  157  TCAGGTGTGCCAGTGGGTGCTGAAATGCAGGAATAGCAAGAACTCGCTGATCCAAATGACAATCCTTAAT
  158  TTGTTGCCCCGCTTGGCTGCATTCCGACCTTCTGCCTTCACAGATACCCAGTATCTCCAAGATACCATGA
  159  ACCATGTCCTAAGCTGTGTCAAGAAGGAGAAGGAACGTACAGCGGCCTTCCAAGCCCTGGGGCTACTTTC
  160  TGTGGCTGTGAGGTCTGAGTTTAAGGTCTATTTGCCTCGCGTGCTGGACATCATCCGAGCGGCCCTGCCC
  161  CCAAAGGACTTCGCCCATAAGAGGCAGAAGGCAATGCAGGTGGATGCCACAGTCTTCACTTGCATCAGCA
  162  TGCTGGCTCGAGCAATGGGGCCAGGCATCCAGCAGGATATCAAGGAGCTGCTGGAGCCCATGCTGGCAGT
  163  GGGACTAAGCCCTGCCCTCACTGCAGTGCTCTACGACCTGAGCCGTCAGATTCCACAGCTAAAGAAGGAC
  164  ATTCAAGATGGGCTACTGAAAATGCTGTCCCTGGTCCTTATGCACAAACCCCTTCGCCACCCAGGCATGC
  165  CCAAGGGCCTGGCCCATCAGCTGGCCTCTCCTGGCCTCACGACCCTCCCTGAGGCCAGCGATGTGGGCAG
  166  CATCACTCTTGCCCTCCGAACGCTTGGCAGCTTTGAATTTGAAGGCCACTCTCTGACCCAATTTGTTCGC
  167  CACTGTGCGGATCATTTCCTGAACAGTGAGCACAAGGAGATCCGCATGGAGGCTGCCCGCACCTGCTCCC
  168  GCCTGCTCACACCCTCCATCCACCTCATCAGTGGCCATGCTCATGTGGTTAGCCAGACCGCAGTGCAAGT
  169  GGTGGCAGATGTGCTTAGCAAACTGCTCGTAGTTGGGATAACAGATCCTGACCCTGACATTCGCTACTGT
  170  GTCTTGGCGTCCCTGGACGAGCGCTTTGATGCACACCTGGCCCAGGCGGAGAACTTGCAGGCCTTGTTTG
  171  TGGCTCTGAATGACCAGGTGTTTGAGATCCGGGAGCTGGCCATCTGCACTGTGGGCCGACTCAGTAGCAT
  172  GAACCCTGCCTTTGTCATGCCTTTCCTGCGCAAGATGCTCATCCAGATTTTGACAGAGTTGGAGCACAGT
  173  GGGATTGGAAGAATCAAAGAGCAGAGTGCCCGCATGCTGGGGCACCTGGTCTCCAATGCCCCCCGACTCA
  174  TCCGCCCCTACATGGAGCCTATTCTGAAGGCATTAATTTTGAAACTGAAAGATCCAGACCCTGATCCAAA
  175  CCCAGGTGTGATCAATAATGTCCTGGCAACAATAGGAGAATTGGCACAGGTTAGTGGCCTGGAAATGAGG
  176  AAATGGGTTGATGAACTTTTTATTATCATCATGGACATGCTCCAGGATTCCTCTTTGTTGGCCAAAAGGC
  177  AGGTGGCTCTGTGGACCCTGGGACAGTTGGTGGCCAGCACTGGCTATGTAGTAGAGCCCTACAGGAAGTA
  178  CCCTACTTTGCTTGAGGTGCTACTGAATTTTCTGAAGACTGAGCAGAACCAGGGTACACGCAGAGAGGCC
  179  ATCCGTGTGTTAGGGCTTTTAGGGGCTTTGGATCCTTACAAGCACAAAGTGAACATTGGCATGATAGACC
  180  AGTCCCGGGATGCCTCTGCTGTCAGCCTGTCAGAATCCAAGTCAAGTCAGGATTCCTCTGACTATAGCAC
  181  TAGTGAAATGCTGGTCAACATGGGAAACTTGCCTCTGGATGAGTTCTACCCAGCTGTGTCCATGGTGGCC
  182  CTGATGCGGATCTTCCGAGACCAGTCACTCTCTCATCATCACACCATGGTTGTCCAGGCCATCACCTTCA
  183  TCTTCAAGTCCCTGGGACTCAAATGTGTGCAGTTCCTGCCCCAGGTCATGCCCACGTTCCTTAACGTCAT
  184  TCGAGTCTGTGATGGGGCCATCCGGGAATTTTTGTTCCAGCAGCTGGGAATGTTGGTGTCCTTTGTGAAG
  185  AGCCACATCAGACCTTATATGGATGAAATAGTCACCCTCATGAGAGAATTCTGGGTCATGAACACCTCAA
  186  TTCAGAGCACGATCATTCTTCTCATTGAGCAAATTGTGGTAGCTCTTGGGGGTGAATTTAAGCTCTACCT
  187  GCCCCAGCTGATCCCACACATGCTGCGTGTCTTCATGCATGACAACAGCCCAGGCCGCATTGTCTCTATC
  188  AAGTTACTGGCTGCAATCCAGCTGTTTGGCGCCAACCTGGATGACTACCTGCATTTACTGCTGCCTCCTA
  189  TTGTTAAGTTGTTTGATGCCCCTGAAGCTCCACTGCCATCTCGAAAGGCAGCGCTAGAGACTGTGGACCG
  190  CCTGACGGAGTCCCTGGATTTCACTGACTATGCCTCCCGGATCATTCACCCTATTGTTCGAACACTGGAC
  191  CAGAGCCCAGAACTGCGCTCCACAGCCATGGACACGCTGTCTTCACTTGTTTTTCAGCTGGGGAAGAAGT
  192  ACCAAATTTTCATTCCAATGGTGAATAAAGTTCTGGTGCGACACCGAATCAATCATCAGCGCTATGATGT
  193  GCTCATCTGCAGAATTGTCAAGGGATACACACTTGCTGATGAAGAGGAGGATCCTTTGATTTACCAGCAT
  194  CGGATGCTTAGGAGTGGCCAAGGGGATGCATTGGCTAGTGGACCAGTGGAAACAGGACCCATGAAGAAAC
  195  TGCACGTCAGCACCATCAACCTCCAAAAGGCCTGGGGCGCTGCCAGGAGGGTCTCCAAAGATGACTGGCT
  196  GGAATGGCTGAGACGGCTGAGCCTGGAGCTGCTGAAGGACTCATCATCGCCCTCCCTGCGCTCCTGCTGG
  197  GCCCTGGCACAGGCCTACAACCCGATGGCCAGGGATCTCTTCAATGCTGCATTTGTGTCCTGCTGGTCTG
  198  AACTGAATGAAGATCAACAGGATGAGCTCATCAGAAGCATCGAGTTGGCCCTCACCTCACAAGACATCGC
  199  TGAAGTCACACAGACCCTCTTAAACTTGGCTGAATTCATGGAACACAGTGACAAGGGCCCCCTGCCACTG
  200  AGAGATGACAATGGCATTGTTCTGCTGGGTGAGAGAGCTGCCAAGTGCCGAGCATATGCCAAAGCACTAC
  201  ACTACAAAGAACTGGAGTTCCAGAAAGGCCCCACCCCTGCCATTCTAGAATCTCTCATCAGCATTAATAA
  202  TAAGCTACAGCAGCCGGAGGCAGCGGCCGGAGTGTTAGAATATGCCATGAAACACTTTGGAGAGCTGGAG
  203  ATCCAGGCTACCTGGTATGAGAAACTGCACGAGTGGGAGGATGCCCTTGTGGCCTATGACAAGAAAATGG
  204  ACACCAACAAGGACGACCCAGAGCTGATGCTGGGCCGCATGCGCTGCCTCGAGGCCTTGGGGGAATGGGG
  205  TCAACTCCACCAGCAGTGCTGTGAAAAGTGGACCCTGGTTAATGATGAGACCCAAGCCAAGATGGCCCGG
  206  ATGGCTGCTGCAGCTGCATGGGGTTTAGGTCAGTGGGACAGCATGGAAGAATACACCTGTATGATCCCTC
  207  GGGACACCCATGATGGGGCATTTTATAGAGCTGTGCTGGCACTGCATCAGGACCTCTTCTCCTTGGCACA
  208  ACAGTGCATTGACAAGGCCAGGGACCTGCTGGATGCTGAATTAACTGCGATGGCAGGAGAGAGTTACAGT
  209  CGGGCATATGGGGCCATGGTTTCTTGCCACATGCTGTCCGAGCTGGAGGAGGTTATCCAGTACAAACTTG
  210  TCCCCGAGCGACGAGAGATCATCCGCCAGATCTGGTGGGAGAGACTGCAGGGCTGCCAGCGTATCGTAGA
  211  GGACTGGCAGAAAATCCTTATGGTGCGGTCCCTTGTGGTCAGCCCTCATGAAGACATGAGAACCTGGCTC
  212  AAGTATGCAAGCCTGTGCGGCAAGAGTGGCAGGCTGGCTCTTGCTCATAAAACTTTAGTGTTGCTCCTGG
  213  GAGTTGATCCGTCTCGGCAACTTGACCATCCTCTGCCAACAGTTCACCCTCAGGTGACCTATGCCTACAT
  214  GAAAAACATGTGGAAGAGTGCCCGCAAGATCGATGCCTTCCAGCACATGCAGCATTTTGTCCAGACCATG
  215  CAGCAACAGGCCCAGCATGCCATCGCTACTGAGGACCAGCAGCATAAGCAGGAACTGCACAAGCTCATGG
  216  CCCGATGCTTCCTGAAACTTGGAGAGTGGCAGCTGAATCTACAGGGCATCAATGAGAGCACAATCCCCAA
  217  AGTGCTGCAGTACTACAGCGCCGCCACAGAGCACGACCGCAGCTGGTACAAGGCCTGGCATGCGTGGGCA
  218  GTGATGAACTTCGAAGCTGTGCTACACTACAAACATCAGAACCAAGCCCGCGATGAGAAGAAGAAACTGC
  219  GTCATGCCAGCGGGGCCAACATCACCAACGCCACCACTGCCGCCACCACGGCCGCCACTGCCACCACCAC
  220  TGCCAGCACCGAGGGCAGCAACAGTGAGAGCGAGGCCGAGAGCACCGAGAACAGCCCCACCCCATCGCCG
  221  CTGCAGAAGAAGGTCACTGAGGATCTGTCCAAAACCCTCCTGATGTACACGGTGCCTGCCGTCCAGGGCT
  222  TCTTCCGTTCCATCTCCTTGTCACGAGGCAACAACCTCCAGGATACACTCAGAGTTCTCACCTTATGGTT
  223  TGATTATGGTCACTGGCCAGATGTCAATGAGGCCTTAGTGGAGGGGGTGAAAGCCATCCAGATTGATACC
  224  TGGCTACAGGTTATACCTCAGCTCATTGCAAGAATTGATACGCCCAGACCCTTGGTGGGACGTCTCATTC
  225  ACCAGCTTCTCACAGACATTGGTCGGTACCACCCCCAGGCCCTCATCTACCCACTGACAGTGGCTTCTAA
  226  GTCTACCACGACAGCCCGGCACAATGCAGCCAACAAGATTCTGAAGAACATGTGTGAGCACAGCAACACC
  227  CTGGTCCAGCAGGCCATGATGGTGAGCGAGGAGCTGATCCGAGTGGCCATCCTCTGGCATGAGATGTGGC
  228  ATGAAGGCCTGGAAGAGGCATCTCGTTTGTACTTTGGGGAAAGGAACGTGAAAGGCATGTTTGAGGTGCT
  229  GGAGCCCTTGCATGCTATGATGGAACGGGGCCCCCAGACTCTGAAGGAAACATCCTTTAATCAGGCCTAT
  230  GGTCGAGATTTAATGGAGGCCCAAGAGTGGTGCAGGAAGTACATGAAATCAGGGAATGTCAAGGACCTCA
  231  CCCAAGCCTGGGACCTCTATTATCATGTGTTCCGACGAATCTCAAAGCAGCTGCCTCAGCTCACATCCTT
  232  AGAGCTGCAATATGTTTCCCCAAAACTTCTGATGTGCCGGGACCTTGAATTGGCTGTGCCAGGAACATAT
  233  GACCCCAACCAGCCAATCATTCGCATTCAGTCCATAGCACCGTCTTTGCAAGTCATCACATCCAAGCAGA
  234  GGCCCCGGAAATTGACACTTATGGGCAGCAACGGACATGAGTTTGTTTTCCTTCTAAAAGGCCATGAAGA
  235  TCTGCGCCAGGATGAGCGTGTGATGCAGCTCTTCGGCCTGGTTAACACCCTTCTGGCCAATGACCCAACA
  236  TCTCTTCGGAAAAACCTCAGCATCCAGAGATACGCTGTCATCCCTTTATCGACCAACTCGGGCCTCATTG
  237  GCTGGGTTCCCCACTGTGACACACTGCACGCCCTCATCCGGGACTACAGGGAGAAGAAGAAGATCCTTCT
  238  CAACATCGAGCATCGCATCATGTTGCGGATGGCTCCGGACTATGACCACTTGACTCTGATGCAGAAGGTG
  239  GAGGTGTTTGAGCATGCCGTCAATAATACAGCTGGGGACGACCTGGCCAAGCTGCTGTGGCTGAAAAGCC
  240  CCAGCTCCGAGGTGTGGTTTGACCGAAGAACCAATTATACCCGTTCTTTAGCGGTCATGTCAATGGTTGG
  241  GTATATTTTAGGCCTGGGAGATAGACACCCATCCAACCTGATGCTGGACCGTCTGAGTGGGAAGATCCTG
  242  CACATTGACTTTGGGGACTGCTTTGAGGTTGCTATGACCCGAGAGAAGTTTCCAGAGAAGATTCCATTTA
  243  GACTAACAAGAATGTTGACCAATGCTATGGAGGTTACAGGCCTGGATGGCAACTACAGAATCACATGCCA
  244  CACAGTGATGGAGGTGCTGCGAGAGCACAAGGACAGTGTCATGGCCGTGCTGGAAGCCTTTGTCTATGAC
  245  CCCTTGCTGAACTGGAGGCTGATGGACACAAATACCAAAGGCAACAAGCGATCCCGAACGAGGACGGATT
  246  CCTACTCTGCTGGCCAGTCAGTCGAAATTTTGGACGGTGTGGAACTTGGAGAGCCAGCCCATAAGAAAAC
  247  GGGGACCACAGTGCCAGAATCTATTCATTCTTTCATTGGAGACGGTTTGGTGAAACCAGAGGCCCTAAAT
  248  AAGAAAGCTATCCAGATTATTAACAGGGTTCGAGATAAGCTCACTGGTCGGGACTTCTCTCATGATGACA
  249  CTTTGGATGTTCCAACGCAAGTTGAGCTGCTCATCAAACAAGCGACATCCCATGAAAACCTCTGCCAGTG
  250  CTATATTGGCTGGTGCCCTTTCTGGTAACTGGAGGCCCAGATGTGCCCATCACGTTTTTTCTGAGGCTTT
  251  TGTACTTTAGTAAATGCTTCCACTAAACTGAAACCATGGTGAGAAAGTTTGACTTTGTTAAATATTTTGA
  252  AATGTAAATGAAAAGAACTACTGTATATTAAAAGTTGGTTTGAACCAACTTTCTAGCTGCTGTTGAAGAA
  253  TATATTGTCAGAAACACAAGGCTTGATTTGGTTCCCAGGACAGTGAAACATAGTAATACCACGTAAATCA
  254  AGCCATTCATTTTGGGGAACAGAAGATCCATAACTTTAGAAATACGGGTTTTGACTTAACTCACAAGAGA
  255  ACTCATCATAAGTACTTGCTGATGGAAGAATGACCTAGTTGCTCCTCTCAACATGGGTACAGCAAACTCA
  256  GCACAGCCAAGAAGCCTCAGGTCGTGGAGAACATGGATTAGGATCCTAGACTGTAAAGACACAGAAGATG
  257  CTGACCTCACCCCTGCCACCTATCCCAAGACCTCACTGGTCTGTGGACAGCAGCAGAAATGTTTGCAAGA
  258  TAGGCCAAAATGAGTACAAAAGGTCTGTCTTCCATCAGACCCAGTGATGCTGCGACTCACACGCTTCAAT
  259  TCAAGACCTGACCGCTAGTAGGGAGGTTTATTCAGATCGCTGGCAGCCTCGGCTGAGCAGATGCACAGAG
  260  GGGATCACTGTGCAGTGGGACCACCCTCACTGGCCTTCTGCAGCAGGGTTCTGGGATGTTTTCAGTGGTC
  261  AAAATACTCTGTTTAGAGCAAGGGCTCAGAAAACAGAAATACTGTCATGGAGGTGCTGAACACAGGGAAG
  262  GTCTGGTACATATTGGAAATTATGAGCAGAACAAATACTCAACTAAATGCACAAAGTATAAAGTGTAGCC
  263  ATGTCTAGACACCATGTTGTATCAGAATAATTTTTGTGCCAATAAATGACATCAGAATTTTAAACATA
   grep -v '>' MTOR.fasta| wc -l
  403  grep -v '>' MTOR.fasta | tr -dc 'A' | wc -c
  404  grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c
  405  grep -v '>' MTOR.fasta | tr -dc 'T' | wc -c
  406  sudo apt install bc
  407  echo "scale=2; ($(grep -v '>' MTOR.fasta |tr -dc 'G' | wc -c) + $(grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c)) / $(grep -v '>' MTOR.fasta |tr -dc 'AGTC' | wc -c) * 100" | bc
  408  echo 2279 C >> obioma.fasta
       echo 2287 G >> obioma.fasta
       echo 2225 A >> obioma.fasta
git clone https://github.com/Marvecodes/Francis-Collin
  414  git add .
  415  git commit -m save
  416  ls
  417  cd Francis-Collin
  418  ls
  419  cd ..
  420  mv obioma.fasta /Francis-Collin/
  421* cp obioma.fasta /Francis-Collin
  422  ls
  423  cd home
  424  cd Home
  425  ls
  426  cd..
  427  cd Francis-Collin
  428  cd ..
  429  ls
  cd obioma
  ls
     history
  cp obioma.sh > Francis-Collin
  cp obioma.sh ../Francis-Collin/
  cd ..
  ls
  cd output
  cd Francis-Collin
  ls
  mv obioma.sh /Script/
  cp obioms.sh /Script/
  cd Script
  cd ..
  mv obioma.sh /Script/
  cp obioma.sh /Script/
  git add .
  git commit -m codehistory
  git push

