  413  git clone https://github.com/Marvecodes/Francis-Collin
  414  git add .
  415  git commit -m save
  416  ls
  417  cd Francis-Collin
  418  ls
  419  cd ..
  420  mv obioma.fasta /Francis-Collin/
  421* cp obioma.fasta /Francis-Collin
  422  ls
  423  cd home
  424  cd Home
  425  ls
  426  cd..
  427  cd Francis-Collin
  428  cd ..
  429  ls
  430  cd obioma
  431  ls
  432  history
  433  echo history >> obioma.sh
  434  ls
  435  echo history
  436  nano
  437  history
obioma_chukueggu@cloudshell:~/obioma$ ^C
obioma_chukueggu@cloudshell:~/obioma$ ^C
obioma_chukueggu@cloudshell:~/obioma$ grep history >> obioma.sh
ls

^[[A^[[A^[[A^[[B^[[B^[[B^[[A^[[A
jiii
cd
history
ls
^C
obioma_chukueggu@cloudshell:~/obioma$ ls
MTOR.fasta  mutantgene.txt  obioma.fasta  obioma.sh  wildtype.fna
obioma_chukueggu@cloudshell:~/obioma$ cp obioma.sh > Francis-Collin
cp: missing destination file operand after 'obioma.sh'
Try 'cp --help' for more information.
obioma_chukueggu@cloudshell:~/obioma$ cp obioma.sh ../Francis-Collin/
obioma_chukueggu@cloudshell:~/obioma$ cd ..
obioma_chukueggu@cloudshell:~$ ls
biocomputing  Francis-Collin  Francis-Collin-1  Home  obioma  output  README-cloudshell.txt
obioma_chukueggu@cloudshell:~$ cd output
-bash: cd: output: Not a directory
obioma_chukueggu@cloudshell:~$ cd Francis-Collin
obioma_chukueggu@cloudshell:~/Francis-Collin$ ls
Francis-Collin  Francis-Collin.pub  obioma.sh  Output  README.md  Script
obioma_chukueggu@cloudshell:~/Francis-Collin$ mv obioma.sh /Script/
mv: cannot create regular file '/Script/': Not a directory
obioma_chukueggu@cloudshell:~/Francis-Collin$ cp obioms.sh /Script/
cp: cannot stat 'obioms.sh': No such file or directory
obioma_chukueggu@cloudshell:~/Francis-Collin$ cd Script
obioma_chukueggu@cloudshell:~/Francis-Collin/Script$ cd ..
obioma_chukueggu@cloudshell:~/Francis-Collin$ mv obioma.sh /Script/
mv: cannot create regular file '/Script/': Not a directory
obioma_chukueggu@cloudshell:~/Francis-Collin$ cp obioma.sh /Script/                                                                                                       
cp: cannot create regular file '/Script/': Not a directory
obioma_chukueggu@cloudshell:~/Francis-Collin$ git add .
obioma_chukueggu@cloudshell:~/Francis-Collin$ git commit -m codehistory
[main a8bc49e] codehistory
 2 files changed, 2 insertions(+)
 create mode 100644 obioma.sh
obioma_chukueggu@cloudshell:~/Francis-Collin$ git push
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (5/5), 396 bytes | 396.00 KiB/s, done.
Total 5 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com:Marvecodes/Francis-Collin.git
   8af3e0d..a8bc49e  main -> main
obioma_chukueggu@cloudshell:~/Francis-Collin$ history
    1  df
    2  df -h
    3  mkdir obioma
    4  mkdir biocomputing && cd biocomputing
    5  wget obioma_chukueggu@cloudshell:~/biocomputing$ wget 
    6  wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna
    7  wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
    8  mv wildtype.fna ../obioma/
    9  rm wildtype.gbk.1
   10  ls
   11  cd ..
   12  cd obioma
   13  grep -n 'tatata' wildtype.fna
   14  grep -n 'tatata' wildtype.fna > mutantgene.txt
   15  echo my favorite gene is MTOR gene
   16  nano
   17  ls
   18  cat MTOR.fasta
   19  grep -v '>' MTOR.fasta | tr -dc 'A' | wc -c
   20  grep -v '>' MTOR.fasta | tr -dc 'G' | wc -c
   21  grep -v '>' MTOR.fasta | tr -dc 'T' | wc -c
   22  grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c
   23  echo "scale=2; ($(grep -v '>' MTOR.fasta |tr -dc 'G' | wc -c) + $(grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c)) / $(grep -v '>' MTOR.fasta |tr -dc 'AGTC' | wc -c) * 100" | bc
   24  sudo apt install bc
   25  echo "scale=2; ($(grep -v '>' MTOR.fasta |tr -dc 'G' | wc -c) + $(grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c)) / $(grep -v '>' MTOR.fasta |tr -dc 'AGTC' | wc -c) * 100" | bc
   26  touch obioma.fasta
   27  echo  1957 T >> obioma.fasta
   28  echo 2279 C >> obioma.fasta
   29  echo 2287 G >> obioma.fasta
   30  echo 2225 A >> obioma.fasta
   31  git push
   32  git
   33  git clone
   34  git clone https://github.com/Marvecodes/Francis-Collin
   35  git push obioma.fasta
   36  git mv obioma.fasta
   37  git push obioma.fasta >> output
   38  git clone https://github.com/Marvecodes/Francis-Collin
   39  cd Francis-Collin
   40  cd ..
   41  cd obioma
   42  cp obioma.fasta ../Francis-collin/
   43  cp obioma.fasta ../Francis-Collin/
   44  ls
   45  cd ..
   46  cd Francis-Collin
   47  mv obioma.fasta /Output/
   48  cd Output
   49  cd ..
   50  mv obioma.fasta >> /Output/
   51  cp obioma.fasta ../Francis-Collin/
   52  cd Francis-Collin
   53  git add .
   54  ls
   55  cd Output
   56  ls
   57  git commit -m (save files)
   58  git commit -m 
   59  git commit -m save
   60  git commit -m (save files) git config --global user.email "obioma.chukueggu@gmail.com" && git config -global user.name "Marvecodes"
   61  git commit -m (save files) git config --global user.email "obioma.chukueggu@gmail.com" && git config -global user.name "Marv-ecodes"
   62  git config --global user.email "obioma.chukueggu@gmail.com" && git config --global user.name "Marvecodes"
   63  git add .
   64  git commit -m save
   65  cd Francis-Collin
   66  ls
   67  cd Output
   68  ls
   69  cd ..
   70  git add .
   71  git commit -m save
   72  git push
   73  git authentication
   74  git push
   75  git remote set-url origin git@github.com:Marvecodes/Francis-Collin.git
   76  git push 
   77  git clone https://github.com/Marvecodes/Francis-Collin.git
   78  git push
   79  cd francis=collin
   80  cd Francis-Collin
   81  git push
   82  SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgU
   83  cls
   84  ls
   85  git push
   86  git link
   87  git init
   88  git push
   89  ssh-keygen -t rsa -b 4096 -C "obioma.chukueggu@gmail.com"
   90  git push
   91  conda create -n <env-name>
   92  ssh-keygen -t rsa -b 4096 -C "obioma.chukueggu@gmail.com"
   93  cat /home/obioma_chukueggu/.ssh/id_rsa.pub
   94  git push
   95  cd biocomputing
   96  cd ..
   97  cd obioma
   98  ls
   99  grep -v '>' MTOR.fasta | wc-l
  100  grep -v '>' MTOR.fasta | wc-C
  101  grep -v '>' MTOR.fasta | wc -l
  102  tail -n +2 MTOR.fasta | wc -l
  103  tail -n +1 MTOR.fasta | wc -l
  104  tail -n MTOR.fasta | wc -l
  105  ls
  106  cd FFRancis-Collin
  107  cd Francis-Collin
  108  ls
  109  cd ..
  110  cd Francis-Collin-1 
  111  ls
  112  cd..
  113  cd ..
  114  rm Francis-Collin-1 
  115  history
  116  ls
  117  mkdir Home
  118  cd Home
  119  mkdir obioma
  120  mkdir biocomputing && cd biocomputing
  121  wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.fna
  122  wget https://raw.githubusercontent.com/josoga2/dataset-repos/main/wildtype.gbk
  123  mv wildtype.fna ../obioma/
  124  rm wildtype.gbk.1
  125  cd ..
  126  cd obioma
  127  grep -n 'tatata' wildtype.fna
  128  grep -n 'tatata' wildtype.fna > mutantgene.txt
  129  echo my favorite gene is MTOR gene
  130  nano
  131  cat MTOR.fasta
  132  3216:agatactaataactctatatatgttgatgcatcagtatctttggctgccgttacttcgaa
  133  3267:agaagcaattgactaagtagtatataaaacggatacgttagtttatctagcttaccatca
  134  obioma_chukueggu@cloudshell:~/Home/obioma$ grep -n 'tatata' wildtype.fna > mutantgene.txt
  135  obioma_chukueggu@cloudshell:~/Home/obioma$ echo my favorite gene is MTOR gene
  136  my favorite gene is MTOR gene
  137  obioma_chukueggu@cloudshell:~/Home/obioma$ nano
  138  obioma_chukueggu@cloudshell:~/Home/obioma$ cat MTOR.fasta
  139  GCTCCCGGCTTAGAGGACAGCGGGGAAGGCGGGCGGTGGGGCAGGGGGCCTGAAGCGGCGGTACCGGTGC
  140  TGGCGGCGGCAGCTGAGGCCTTGGCCGAAGCCGCGCGAATATTAAAGGAAACTTCTCTCTAAAGAACCTC
  141  AGGGCAAGATGCTTGGAACCGGACCTGCCGCCGCCACCACCGCTGCCACCACATCTAGCAATGTGAGCGT
  142  CCTGCAGCAGTTTGCCAGTGGCCTAAAGAGCCGGAATGAGGAAACCAGGGCCAAAGCCGCCAAGGAGCTC
  143  CAGCACTATGTCACCATGGAACTCCGAGAGATGAGTCAAGAGGAGTCTACTCGCTTCTATGACCAACTGA
  144  ACCATCACATTTTTGAATTGGTTTCCAGCTCAGATGCCAATGAGAGGAAAGGTGGCATCTTGGCCATAGC
  145  TAGCCTCATAGGAGTGGAAGGTGGGAATGCCACCCGAATTGGCAGATTTGCCAACTATCTTCGGAACCTC
  146  CTCCCCTCCAATGACCCAGTTGTCATGGAAATGGCATCCAAGGCCATTGGCCGTCTTGCCATGGCAGGGG
  147  ACACTTTTACCGCTGAGTACGTGGAATTTGAGGTGAAGCGAGCCCTGGAATGGCTGGGTGCTGACCGCAA
  148  TGAGGGCCGGAGACATGCAGCTGTCCTGGTTCTCCGTGAGCTGGCCATCAGCGTCCCTACCTTCTTCTTC
  149  CAGCAAGTGCAACCCTTCTTTGACAACATTTTTGTGGCCGTGTGGGACCCCAAACAGGCCATCCGTGAGG
  150  GAGCTGTAGCCGCCCTTCGTGCCTGTCTGATTCTCACAACCCAGCGTGAGCCGAAGGAGATGCAGAAGCC
  151  TCAGTGGTACAGGCACACATTTGAAGAAGCAGAGAAGGGATTTGATGAGACCTTGGCCAAAGAGAAGGGC
  152  ATGAATCGGGATGATCGGATCCATGGAGCCTTGTTGATCCTTAACGAGCTGGTCCGAATCAGCAGCATGG
  153  AGGGAGAGCGTCTGAGAGAAGAAATGGAAGAAATCACACAGCAGCAGCTGGTACACGACAAGTACTGCAA
  154  AGATCTCATGGGCTTCGGAACAAAACCTCGTCACATTACCCCCTTCACCAGTTTCCAGGCTGTACAGCCC
  155  CAGCAGTCAAATGCCTTGGTGGGGCTGCTGGGGTACAGCTCTCACCAAGGCCTCATGGGATTTGGGACCT
  156  CCCCCAGTCCAGCTAAGTCCACCCTGGTGGAGAGCCGGTGTTGCAGAGACTTGATGGAGGAGAAATTTGA
  157  TCAGGTGTGCCAGTGGGTGCTGAAATGCAGGAATAGCAAGAACTCGCTGATCCAAATGACAATCCTTAAT
  158  TTGTTGCCCCGCTTGGCTGCATTCCGACCTTCTGCCTTCACAGATACCCAGTATCTCCAAGATACCATGA
  159  ACCATGTCCTAAGCTGTGTCAAGAAGGAGAAGGAACGTACAGCGGCCTTCCAAGCCCTGGGGCTACTTTC
  160  TGTGGCTGTGAGGTCTGAGTTTAAGGTCTATTTGCCTCGCGTGCTGGACATCATCCGAGCGGCCCTGCCC
  161  CCAAAGGACTTCGCCCATAAGAGGCAGAAGGCAATGCAGGTGGATGCCACAGTCTTCACTTGCATCAGCA
  162  TGCTGGCTCGAGCAATGGGGCCAGGCATCCAGCAGGATATCAAGGAGCTGCTGGAGCCCATGCTGGCAGT
  163  GGGACTAAGCCCTGCCCTCACTGCAGTGCTCTACGACCTGAGCCGTCAGATTCCACAGCTAAAGAAGGAC
  164  ATTCAAGATGGGCTACTGAAAATGCTGTCCCTGGTCCTTATGCACAAACCCCTTCGCCACCCAGGCATGC
  165  CCAAGGGCCTGGCCCATCAGCTGGCCTCTCCTGGCCTCACGACCCTCCCTGAGGCCAGCGATGTGGGCAG
  166  CATCACTCTTGCCCTCCGAACGCTTGGCAGCTTTGAATTTGAAGGCCACTCTCTGACCCAATTTGTTCGC
  167  CACTGTGCGGATCATTTCCTGAACAGTGAGCACAAGGAGATCCGCATGGAGGCTGCCCGCACCTGCTCCC
  168  GCCTGCTCACACCCTCCATCCACCTCATCAGTGGCCATGCTCATGTGGTTAGCCAGACCGCAGTGCAAGT
  169  GGTGGCAGATGTGCTTAGCAAACTGCTCGTAGTTGGGATAACAGATCCTGACCCTGACATTCGCTACTGT
  170  GTCTTGGCGTCCCTGGACGAGCGCTTTGATGCACACCTGGCCCAGGCGGAGAACTTGCAGGCCTTGTTTG
  171  TGGCTCTGAATGACCAGGTGTTTGAGATCCGGGAGCTGGCCATCTGCACTGTGGGCCGACTCAGTAGCAT
  172  GAACCCTGCCTTTGTCATGCCTTTCCTGCGCAAGATGCTCATCCAGATTTTGACAGAGTTGGAGCACAGT
  173  GGGATTGGAAGAATCAAAGAGCAGAGTGCCCGCATGCTGGGGCACCTGGTCTCCAATGCCCCCCGACTCA
  174  TCCGCCCCTACATGGAGCCTATTCTGAAGGCATTAATTTTGAAACTGAAAGATCCAGACCCTGATCCAAA
  175  CCCAGGTGTGATCAATAATGTCCTGGCAACAATAGGAGAATTGGCACAGGTTAGTGGCCTGGAAATGAGG
  176  AAATGGGTTGATGAACTTTTTATTATCATCATGGACATGCTCCAGGATTCCTCTTTGTTGGCCAAAAGGC
  177  AGGTGGCTCTGTGGACCCTGGGACAGTTGGTGGCCAGCACTGGCTATGTAGTAGAGCCCTACAGGAAGTA
  178  CCCTACTTTGCTTGAGGTGCTACTGAATTTTCTGAAGACTGAGCAGAACCAGGGTACACGCAGAGAGGCC
  179  ATCCGTGTGTTAGGGCTTTTAGGGGCTTTGGATCCTTACAAGCACAAAGTGAACATTGGCATGATAGACC
  180  AGTCCCGGGATGCCTCTGCTGTCAGCCTGTCAGAATCCAAGTCAAGTCAGGATTCCTCTGACTATAGCAC
  181  TAGTGAAATGCTGGTCAACATGGGAAACTTGCCTCTGGATGAGTTCTACCCAGCTGTGTCCATGGTGGCC
  182  CTGATGCGGATCTTCCGAGACCAGTCACTCTCTCATCATCACACCATGGTTGTCCAGGCCATCACCTTCA
  183  TCTTCAAGTCCCTGGGACTCAAATGTGTGCAGTTCCTGCCCCAGGTCATGCCCACGTTCCTTAACGTCAT
  184  TCGAGTCTGTGATGGGGCCATCCGGGAATTTTTGTTCCAGCAGCTGGGAATGTTGGTGTCCTTTGTGAAG
  185  AGCCACATCAGACCTTATATGGATGAAATAGTCACCCTCATGAGAGAATTCTGGGTCATGAACACCTCAA
  186  TTCAGAGCACGATCATTCTTCTCATTGAGCAAATTGTGGTAGCTCTTGGGGGTGAATTTAAGCTCTACCT
  187  GCCCCAGCTGATCCCACACATGCTGCGTGTCTTCATGCATGACAACAGCCCAGGCCGCATTGTCTCTATC
  188  AAGTTACTGGCTGCAATCCAGCTGTTTGGCGCCAACCTGGATGACTACCTGCATTTACTGCTGCCTCCTA
  189  TTGTTAAGTTGTTTGATGCCCCTGAAGCTCCACTGCCATCTCGAAAGGCAGCGCTAGAGACTGTGGACCG
  190  CCTGACGGAGTCCCTGGATTTCACTGACTATGCCTCCCGGATCATTCACCCTATTGTTCGAACACTGGAC
  191  CAGAGCCCAGAACTGCGCTCCACAGCCATGGACACGCTGTCTTCACTTGTTTTTCAGCTGGGGAAGAAGT
  192  ACCAAATTTTCATTCCAATGGTGAATAAAGTTCTGGTGCGACACCGAATCAATCATCAGCGCTATGATGT
  193  GCTCATCTGCAGAATTGTCAAGGGATACACACTTGCTGATGAAGAGGAGGATCCTTTGATTTACCAGCAT
  194  CGGATGCTTAGGAGTGGCCAAGGGGATGCATTGGCTAGTGGACCAGTGGAAACAGGACCCATGAAGAAAC
  195  TGCACGTCAGCACCATCAACCTCCAAAAGGCCTGGGGCGCTGCCAGGAGGGTCTCCAAAGATGACTGGCT
  196  GGAATGGCTGAGACGGCTGAGCCTGGAGCTGCTGAAGGACTCATCATCGCCCTCCCTGCGCTCCTGCTGG
  197  GCCCTGGCACAGGCCTACAACCCGATGGCCAGGGATCTCTTCAATGCTGCATTTGTGTCCTGCTGGTCTG
  198  AACTGAATGAAGATCAACAGGATGAGCTCATCAGAAGCATCGAGTTGGCCCTCACCTCACAAGACATCGC
  199  TGAAGTCACACAGACCCTCTTAAACTTGGCTGAATTCATGGAACACAGTGACAAGGGCCCCCTGCCACTG
  200  AGAGATGACAATGGCATTGTTCTGCTGGGTGAGAGAGCTGCCAAGTGCCGAGCATATGCCAAAGCACTAC
  201  ACTACAAAGAACTGGAGTTCCAGAAAGGCCCCACCCCTGCCATTCTAGAATCTCTCATCAGCATTAATAA
  202  TAAGCTACAGCAGCCGGAGGCAGCGGCCGGAGTGTTAGAATATGCCATGAAACACTTTGGAGAGCTGGAG
  203  ATCCAGGCTACCTGGTATGAGAAACTGCACGAGTGGGAGGATGCCCTTGTGGCCTATGACAAGAAAATGG
  204  ACACCAACAAGGACGACCCAGAGCTGATGCTGGGCCGCATGCGCTGCCTCGAGGCCTTGGGGGAATGGGG
  205  TCAACTCCACCAGCAGTGCTGTGAAAAGTGGACCCTGGTTAATGATGAGACCCAAGCCAAGATGGCCCGG
  206  ATGGCTGCTGCAGCTGCATGGGGTTTAGGTCAGTGGGACAGCATGGAAGAATACACCTGTATGATCCCTC
  207  GGGACACCCATGATGGGGCATTTTATAGAGCTGTGCTGGCACTGCATCAGGACCTCTTCTCCTTGGCACA
  208  ACAGTGCATTGACAAGGCCAGGGACCTGCTGGATGCTGAATTAACTGCGATGGCAGGAGAGAGTTACAGT
  209  CGGGCATATGGGGCCATGGTTTCTTGCCACATGCTGTCCGAGCTGGAGGAGGTTATCCAGTACAAACTTG
  210  TCCCCGAGCGACGAGAGATCATCCGCCAGATCTGGTGGGAGAGACTGCAGGGCTGCCAGCGTATCGTAGA
  211  GGACTGGCAGAAAATCCTTATGGTGCGGTCCCTTGTGGTCAGCCCTCATGAAGACATGAGAACCTGGCTC
  212  AAGTATGCAAGCCTGTGCGGCAAGAGTGGCAGGCTGGCTCTTGCTCATAAAACTTTAGTGTTGCTCCTGG
  213  GAGTTGATCCGTCTCGGCAACTTGACCATCCTCTGCCAACAGTTCACCCTCAGGTGACCTATGCCTACAT
  214  GAAAAACATGTGGAAGAGTGCCCGCAAGATCGATGCCTTCCAGCACATGCAGCATTTTGTCCAGACCATG
  215  CAGCAACAGGCCCAGCATGCCATCGCTACTGAGGACCAGCAGCATAAGCAGGAACTGCACAAGCTCATGG
  216  CCCGATGCTTCCTGAAACTTGGAGAGTGGCAGCTGAATCTACAGGGCATCAATGAGAGCACAATCCCCAA
  217  AGTGCTGCAGTACTACAGCGCCGCCACAGAGCACGACCGCAGCTGGTACAAGGCCTGGCATGCGTGGGCA
  218  GTGATGAACTTCGAAGCTGTGCTACACTACAAACATCAGAACCAAGCCCGCGATGAGAAGAAGAAACTGC
  219  GTCATGCCAGCGGGGCCAACATCACCAACGCCACCACTGCCGCCACCACGGCCGCCACTGCCACCACCAC
  220  TGCCAGCACCGAGGGCAGCAACAGTGAGAGCGAGGCCGAGAGCACCGAGAACAGCCCCACCCCATCGCCG
  221  CTGCAGAAGAAGGTCACTGAGGATCTGTCCAAAACCCTCCTGATGTACACGGTGCCTGCCGTCCAGGGCT
  222  TCTTCCGTTCCATCTCCTTGTCACGAGGCAACAACCTCCAGGATACACTCAGAGTTCTCACCTTATGGTT
  223  TGATTATGGTCACTGGCCAGATGTCAATGAGGCCTTAGTGGAGGGGGTGAAAGCCATCCAGATTGATACC
  224  TGGCTACAGGTTATACCTCAGCTCATTGCAAGAATTGATACGCCCAGACCCTTGGTGGGACGTCTCATTC
  225  ACCAGCTTCTCACAGACATTGGTCGGTACCACCCCCAGGCCCTCATCTACCCACTGACAGTGGCTTCTAA
  226  GTCTACCACGACAGCCCGGCACAATGCAGCCAACAAGATTCTGAAGAACATGTGTGAGCACAGCAACACC
  227  CTGGTCCAGCAGGCCATGATGGTGAGCGAGGAGCTGATCCGAGTGGCCATCCTCTGGCATGAGATGTGGC
  228  ATGAAGGCCTGGAAGAGGCATCTCGTTTGTACTTTGGGGAAAGGAACGTGAAAGGCATGTTTGAGGTGCT
  229  GGAGCCCTTGCATGCTATGATGGAACGGGGCCCCCAGACTCTGAAGGAAACATCCTTTAATCAGGCCTAT
  230  GGTCGAGATTTAATGGAGGCCCAAGAGTGGTGCAGGAAGTACATGAAATCAGGGAATGTCAAGGACCTCA
  231  CCCAAGCCTGGGACCTCTATTATCATGTGTTCCGACGAATCTCAAAGCAGCTGCCTCAGCTCACATCCTT
  232  AGAGCTGCAATATGTTTCCCCAAAACTTCTGATGTGCCGGGACCTTGAATTGGCTGTGCCAGGAACATAT
  233  GACCCCAACCAGCCAATCATTCGCATTCAGTCCATAGCACCGTCTTTGCAAGTCATCACATCCAAGCAGA
  234  GGCCCCGGAAATTGACACTTATGGGCAGCAACGGACATGAGTTTGTTTTCCTTCTAAAAGGCCATGAAGA
  235  TCTGCGCCAGGATGAGCGTGTGATGCAGCTCTTCGGCCTGGTTAACACCCTTCTGGCCAATGACCCAACA
  236  TCTCTTCGGAAAAACCTCAGCATCCAGAGATACGCTGTCATCCCTTTATCGACCAACTCGGGCCTCATTG
  237  GCTGGGTTCCCCACTGTGACACACTGCACGCCCTCATCCGGGACTACAGGGAGAAGAAGAAGATCCTTCT
  238  CAACATCGAGCATCGCATCATGTTGCGGATGGCTCCGGACTATGACCACTTGACTCTGATGCAGAAGGTG
  239  GAGGTGTTTGAGCATGCCGTCAATAATACAGCTGGGGACGACCTGGCCAAGCTGCTGTGGCTGAAAAGCC
  240  CCAGCTCCGAGGTGTGGTTTGACCGAAGAACCAATTATACCCGTTCTTTAGCGGTCATGTCAATGGTTGG
  241  GTATATTTTAGGCCTGGGAGATAGACACCCATCCAACCTGATGCTGGACCGTCTGAGTGGGAAGATCCTG
  242  CACATTGACTTTGGGGACTGCTTTGAGGTTGCTATGACCCGAGAGAAGTTTCCAGAGAAGATTCCATTTA
  243  GACTAACAAGAATGTTGACCAATGCTATGGAGGTTACAGGCCTGGATGGCAACTACAGAATCACATGCCA
  244  CACAGTGATGGAGGTGCTGCGAGAGCACAAGGACAGTGTCATGGCCGTGCTGGAAGCCTTTGTCTATGAC
  245  CCCTTGCTGAACTGGAGGCTGATGGACACAAATACCAAAGGCAACAAGCGATCCCGAACGAGGACGGATT
  246  CCTACTCTGCTGGCCAGTCAGTCGAAATTTTGGACGGTGTGGAACTTGGAGAGCCAGCCCATAAGAAAAC
  247  GGGGACCACAGTGCCAGAATCTATTCATTCTTTCATTGGAGACGGTTTGGTGAAACCAGAGGCCCTAAAT
  248  AAGAAAGCTATCCAGATTATTAACAGGGTTCGAGATAAGCTCACTGGTCGGGACTTCTCTCATGATGACA
  249  CTTTGGATGTTCCAACGCAAGTTGAGCTGCTCATCAAACAAGCGACATCCCATGAAAACCTCTGCCAGTG
  250  CTATATTGGCTGGTGCCCTTTCTGGTAACTGGAGGCCCAGATGTGCCCATCACGTTTTTTCTGAGGCTTT
  251  TGTACTTTAGTAAATGCTTCCACTAAACTGAAACCATGGTGAGAAAGTTTGACTTTGTTAAATATTTTGA
  252  AATGTAAATGAAAAGAACTACTGTATATTAAAAGTTGGTTTGAACCAACTTTCTAGCTGCTGTTGAAGAA
  253  TATATTGTCAGAAACACAAGGCTTGATTTGGTTCCCAGGACAGTGAAACATAGTAATACCACGTAAATCA
  254  AGCCATTCATTTTGGGGAACAGAAGATCCATAACTTTAGAAATACGGGTTTTGACTTAACTCACAAGAGA
  255  ACTCATCATAAGTACTTGCTGATGGAAGAATGACCTAGTTGCTCCTCTCAACATGGGTACAGCAAACTCA
  256  GCACAGCCAAGAAGCCTCAGGTCGTGGAGAACATGGATTAGGATCCTAGACTGTAAAGACACAGAAGATG
  257  CTGACCTCACCCCTGCCACCTATCCCAAGACCTCACTGGTCTGTGGACAGCAGCAGAAATGTTTGCAAGA
  258  TAGGCCAAAATGAGTACAAAAGGTCTGTCTTCCATCAGACCCAGTGATGCTGCGACTCACACGCTTCAAT
  259  TCAAGACCTGACCGCTAGTAGGGAGGTTTATTCAGATCGCTGGCAGCCTCGGCTGAGCAGATGCACAGAG
  260  GGGATCACTGTGCAGTGGGACCACCCTCACTGGCCTTCTGCAGCAGGGTTCTGGGATGTTTTCAGTGGTC
  261  AAAATACTCTGTTTAGAGCAAGGGCTCAGAAAACAGAAATACTGTCATGGAGGTGCTGAACACAGGGAAG
  262  GTCTGGTACATATTGGAAATTATGAGCAGAACAAATACTCAACTAAATGCACAAAGTATAAAGTGTAGCC
  263  ATGTCTAGACACCATGTTGTATCAGAATAATTTTTGTGCCAATAAATGACATCAGAATTTTAAACATA
  264  obioma_chukueggu@cloudshell:~/Home/obioma$   grep -v '>' MTOR.fasta| wc-l
  265  -bash: wc-l: command not found
  266  obioma_chukueggu@cloudshell:~/Home/obioma$ 
  267  3216:agatactaataactctatatatgttgatgcatcagtatctttggctgccgttacttcgaa
  268  3267:agaagcaattgactaagtagtatataaaacggatacgttagtttatctagcttaccatca
  269  obioma_chukueggu@cloudshell:~/Home/obioma$ grep -n 'tatata' wildtype.fna > mutantgene.txt
  270  obioma_chukueggu@cloudshell:~/Home/obioma$ echo my favorite gene is MTOR gene
  271  my favorite gene is MTOR gene
  272  obioma_chukueggu@cloudshell:~/Home/obioma$ nano
  273  obioma_chukueggu@cloudshell:~/Home/obioma$ cat MTOR.fasta
  274  GCTCCCGGCTTAGAGGACAGCGGGGAAGGCGGGCGGTGGGGCAGGGGGCCTGAAGCGGCGGTACCGGTGC
  275  TGGCGGCGGCAGCTGAGGCCTTGGCCGAAGCCGCGCGAATATTAAAGGAAACTTCTCTCTAAAGAACCTC
  276  AGGGCAAGATGCTTGGAACCGGACCTGCCGCCGCCACCACCGCTGCCACCACATCTAGCAATGTGAGCGT
  277  CCTGCAGCAGTTTGCCAGTGGCCTAAAGAGCCGGAATGAGGAAACCAGGGCCAAAGCCGCCAAGGAGCTC
  278  CAGCACTATGTCACCATGGAACTCCGAGAGATGAGTCAAGAGGAGTCTACTCGCTTCTATGACCAACTGA
  279  ACCATCACATTTTTGAATTGGTTTCCAGCTCAGATGCCAATGAGAGGAAAGGTGGCATCTTGGCCATAGC
  280  TAGCCTCATAGGAGTGGAAGGTGGGAATGCCACCCGAATTGGCAGATTTGCCAACTATCTTCGGAACCTC
  281  CTCCCCTCCAATGACCCAGTTGTCATGGAAATGGCATCCAAGGCCATTGGCCGTCTTGCCATGGCAGGGG
  282  ACACTTTTACCGCTGAGTACGTGGAATTTGAGGTGAAGCGAGCCCTGGAATGGCTGGGTGCTGACCGCAA
  283  TGAGGGCCGGAGACATGCAGCTGTCCTGGTTCTCCGTGAGCTGGCCATCAGCGTCCCTACCTTCTTCTTC
  284  CAGCAAGTGCAACCCTTCTTTGACAACATTTTTGTGGCCGTGTGGGACCCCAAACAGGCCATCCGTGAGG
  285  GAGCTGTAGCCGCCCTTCGTGCCTGTCTGATTCTCACAACCCAGCGTGAGCCGAAGGAGATGCAGAAGCC
  286  TCAGTGGTACAGGCACACATTTGAAGAAGCAGAGAAGGGATTTGATGAGACCTTGGCCAAAGAGAAGGGC
  287  ATGAATCGGGATGATCGGATCCATGGAGCCTTGTTGATCCTTAACGAGCTGGTCCGAATCAGCAGCATGG
  288  AGGGAGAGCGTCTGAGAGAAGAAATGGAAGAAATCACACAGCAGCAGCTGGTACACGACAAGTACTGCAA
  289  AGATCTCATGGGCTTCGGAACAAAACCTCGTCACATTACCCCCTTCACCAGTTTCCAGGCTGTACAGCCC
  290  CAGCAGTCAAATGCCTTGGTGGGGCTGCTGGGGTACAGCTCTCACCAAGGCCTCATGGGATTTGGGACCT
  291  CCCCCAGTCCAGCTAAGTCCACCCTGGTGGAGAGCCGGTGTTGCAGAGACTTGATGGAGGAGAAATTTGA
  292  TCAGGTGTGCCAGTGGGTGCTGAAATGCAGGAATAGCAAGAACTCGCTGATCCAAATGACAATCCTTAAT
  293  TTGTTGCCCCGCTTGGCTGCATTCCGACCTTCTGCCTTCACAGATACCCAGTATCTCCAAGATACCATGA
  294  ACCATGTCCTAAGCTGTGTCAAGAAGGAGAAGGAACGTACAGCGGCCTTCCAAGCCCTGGGGCTACTTTC
  295  TGTGGCTGTGAGGTCTGAGTTTAAGGTCTATTTGCCTCGCGTGCTGGACATCATCCGAGCGGCCCTGCCC
  296  CCAAAGGACTTCGCCCATAAGAGGCAGAAGGCAATGCAGGTGGATGCCACAGTCTTCACTTGCATCAGCA
  297  TGCTGGCTCGAGCAATGGGGCCAGGCATCCAGCAGGATATCAAGGAGCTGCTGGAGCCCATGCTGGCAGT
  298  GGGACTAAGCCCTGCCCTCACTGCAGTGCTCTACGACCTGAGCCGTCAGATTCCACAGCTAAAGAAGGAC
  299  ATTCAAGATGGGCTACTGAAAATGCTGTCCCTGGTCCTTATGCACAAACCCCTTCGCCACCCAGGCATGC
  300  CCAAGGGCCTGGCCCATCAGCTGGCCTCTCCTGGCCTCACGACCCTCCCTGAGGCCAGCGATGTGGGCAG
  301  CATCACTCTTGCCCTCCGAACGCTTGGCAGCTTTGAATTTGAAGGCCACTCTCTGACCCAATTTGTTCGC
  302  CACTGTGCGGATCATTTCCTGAACAGTGAGCACAAGGAGATCCGCATGGAGGCTGCCCGCACCTGCTCCC
  303  GCCTGCTCACACCCTCCATCCACCTCATCAGTGGCCATGCTCATGTGGTTAGCCAGACCGCAGTGCAAGT
  304  GGTGGCAGATGTGCTTAGCAAACTGCTCGTAGTTGGGATAACAGATCCTGACCCTGACATTCGCTACTGT
  305  GTCTTGGCGTCCCTGGACGAGCGCTTTGATGCACACCTGGCCCAGGCGGAGAACTTGCAGGCCTTGTTTG
  306  TGGCTCTGAATGACCAGGTGTTTGAGATCCGGGAGCTGGCCATCTGCACTGTGGGCCGACTCAGTAGCAT
  307  GAACCCTGCCTTTGTCATGCCTTTCCTGCGCAAGATGCTCATCCAGATTTTGACAGAGTTGGAGCACAGT
  308  GGGATTGGAAGAATCAAAGAGCAGAGTGCCCGCATGCTGGGGCACCTGGTCTCCAATGCCCCCCGACTCA
  309  TCCGCCCCTACATGGAGCCTATTCTGAAGGCATTAATTTTGAAACTGAAAGATCCAGACCCTGATCCAAA
  310  CCCAGGTGTGATCAATAATGTCCTGGCAACAATAGGAGAATTGGCACAGGTTAGTGGCCTGGAAATGAGG
  311  AAATGGGTTGATGAACTTTTTATTATCATCATGGACATGCTCCAGGATTCCTCTTTGTTGGCCAAAAGGC
  312  AGGTGGCTCTGTGGACCCTGGGACAGTTGGTGGCCAGCACTGGCTATGTAGTAGAGCCCTACAGGAAGTA
  313  CCCTACTTTGCTTGAGGTGCTACTGAATTTTCTGAAGACTGAGCAGAACCAGGGTACACGCAGAGAGGCC
  314  ATCCGTGTGTTAGGGCTTTTAGGGGCTTTGGATCCTTACAAGCACAAAGTGAACATTGGCATGATAGACC
  315  AGTCCCGGGATGCCTCTGCTGTCAGCCTGTCAGAATCCAAGTCAAGTCAGGATTCCTCTGACTATAGCAC
  316  TAGTGAAATGCTGGTCAACATGGGAAACTTGCCTCTGGATGAGTTCTACCCAGCTGTGTCCATGGTGGCC
  317  CTGATGCGGATCTTCCGAGACCAGTCACTCTCTCATCATCACACCATGGTTGTCCAGGCCATCACCTTCA
  318  TCTTCAAGTCCCTGGGACTCAAATGTGTGCAGTTCCTGCCCCAGGTCATGCCCACGTTCCTTAACGTCAT
  319  TCGAGTCTGTGATGGGGCCATCCGGGAATTTTTGTTCCAGCAGCTGGGAATGTTGGTGTCCTTTGTGAAG
  320  AGCCACATCAGACCTTATATGGATGAAATAGTCACCCTCATGAGAGAATTCTGGGTCATGAACACCTCAA
  321  TTCAGAGCACGATCATTCTTCTCATTGAGCAAATTGTGGTAGCTCTTGGGGGTGAATTTAAGCTCTACCT
  322  GCCCCAGCTGATCCCACACATGCTGCGTGTCTTCATGCATGACAACAGCCCAGGCCGCATTGTCTCTATC
  323  AAGTTACTGGCTGCAATCCAGCTGTTTGGCGCCAACCTGGATGACTACCTGCATTTACTGCTGCCTCCTA
  324  TTGTTAAGTTGTTTGATGCCCCTGAAGCTCCACTGCCATCTCGAAAGGCAGCGCTAGAGACTGTGGACCG
  325  CCTGACGGAGTCCCTGGATTTCACTGACTATGCCTCCCGGATCATTCACCCTATTGTTCGAACACTGGAC
  326  CAGAGCCCAGAACTGCGCTCCACAGCCATGGACACGCTGTCTTCACTTGTTTTTCAGCTGGGGAAGAAGT
  327  ACCAAATTTTCATTCCAATGGTGAATAAAGTTCTGGTGCGACACCGAATCAATCATCAGCGCTATGATGT
  328  GCTCATCTGCAGAATTGTCAAGGGATACACACTTGCTGATGAAGAGGAGGATCCTTTGATTTACCAGCAT
  329  CGGATGCTTAGGAGTGGCCAAGGGGATGCATTGGCTAGTGGACCAGTGGAAACAGGACCCATGAAGAAAC
  330  TGCACGTCAGCACCATCAACCTCCAAAAGGCCTGGGGCGCTGCCAGGAGGGTCTCCAAAGATGACTGGCT
  331  GGAATGGCTGAGACGGCTGAGCCTGGAGCTGCTGAAGGACTCATCATCGCCCTCCCTGCGCTCCTGCTGG
  332  GCCCTGGCACAGGCCTACAACCCGATGGCCAGGGATCTCTTCAATGCTGCATTTGTGTCCTGCTGGTCTG
  333  AACTGAATGAAGATCAACAGGATGAGCTCATCAGAAGCATCGAGTTGGCCCTCACCTCACAAGACATCGC
  334  TGAAGTCACACAGACCCTCTTAAACTTGGCTGAATTCATGGAACACAGTGACAAGGGCCCCCTGCCACTG
  335  AGAGATGACAATGGCATTGTTCTGCTGGGTGAGAGAGCTGCCAAGTGCCGAGCATATGCCAAAGCACTAC
  336  ACTACAAAGAACTGGAGTTCCAGAAAGGCCCCACCCCTGCCATTCTAGAATCTCTCATCAGCATTAATAA
  337  TAAGCTACAGCAGCCGGAGGCAGCGGCCGGAGTGTTAGAATATGCCATGAAACACTTTGGAGAGCTGGAG
  338  ATCCAGGCTACCTGGTATGAGAAACTGCACGAGTGGGAGGATGCCCTTGTGGCCTATGACAAGAAAATGG
  339  ACACCAACAAGGACGACCCAGAGCTGATGCTGGGCCGCATGCGCTGCCTCGAGGCCTTGGGGGAATGGGG
  340  TCAACTCCACCAGCAGTGCTGTGAAAAGTGGACCCTGGTTAATGATGAGACCCAAGCCAAGATGGCCCGG
  341  ATGGCTGCTGCAGCTGCATGGGGTTTAGGTCAGTGGGACAGCATGGAAGAATACACCTGTATGATCCCTC
  342  GGGACACCCATGATGGGGCATTTTATAGAGCTGTGCTGGCACTGCATCAGGACCTCTTCTCCTTGGCACA
  343  ACAGTGCATTGACAAGGCCAGGGACCTGCTGGATGCTGAATTAACTGCGATGGCAGGAGAGAGTTACAGT
  344  CGGGCATATGGGGCCATGGTTTCTTGCCACATGCTGTCCGAGCTGGAGGAGGTTATCCAGTACAAACTTG
  345  TCCCCGAGCGACGAGAGATCATCCGCCAGATCTGGTGGGAGAGACTGCAGGGCTGCCAGCGTATCGTAGA
  346  GGACTGGCAGAAAATCCTTATGGTGCGGTCCCTTGTGGTCAGCCCTCATGAAGACATGAGAACCTGGCTC
  347  AAGTATGCAAGCCTGTGCGGCAAGAGTGGCAGGCTGGCTCTTGCTCATAAAACTTTAGTGTTGCTCCTGG
  348  GAGTTGATCCGTCTCGGCAACTTGACCATCCTCTGCCAACAGTTCACCCTCAGGTGACCTATGCCTACAT
  349  GAAAAACATGTGGAAGAGTGCCCGCAAGATCGATGCCTTCCAGCACATGCAGCATTTTGTCCAGACCATG
  350  CAGCAACAGGCCCAGCATGCCATCGCTACTGAGGACCAGCAGCATAAGCAGGAACTGCACAAGCTCATGG
  351  CCCGATGCTTCCTGAAACTTGGAGAGTGGCAGCTGAATCTACAGGGCATCAATGAGAGCACAATCCCCAA
  352  AGTGCTGCAGTACTACAGCGCCGCCACAGAGCACGACCGCAGCTGGTACAAGGCCTGGCATGCGTGGGCA
  353  GTGATGAACTTCGAAGCTGTGCTACACTACAAACATCAGAACCAAGCCCGCGATGAGAAGAAGAAACTGC
  354  GTCATGCCAGCGGGGCCAACATCACCAACGCCACCACTGCCGCCACCACGGCCGCCACTGCCACCACCAC
  355  TGCCAGCACCGAGGGCAGCAACAGTGAGAGCGAGGCCGAGAGCACCGAGAACAGCCCCACCCCATCGCCG
  356  CTGCAGAAGAAGGTCACTGAGGATCTGTCCAAAACCCTCCTGATGTACACGGTGCCTGCCGTCCAGGGCT
  357  TCTTCCGTTCCATCTCCTTGTCACGAGGCAACAACCTCCAGGATACACTCAGAGTTCTCACCTTATGGTT
  358  TGATTATGGTCACTGGCCAGATGTCAATGAGGCCTTAGTGGAGGGGGTGAAAGCCATCCAGATTGATACC
  359  TGGCTACAGGTTATACCTCAGCTCATTGCAAGAATTGATACGCCCAGACCCTTGGTGGGACGTCTCATTC
  360  ACCAGCTTCTCACAGACATTGGTCGGTACCACCCCCAGGCCCTCATCTACCCACTGACAGTGGCTTCTAA
  361  GTCTACCACGACAGCCCGGCACAATGCAGCCAACAAGATTCTGAAGAACATGTGTGAGCACAGCAACACC
  362  CTGGTCCAGCAGGCCATGATGGTGAGCGAGGAGCTGATCCGAGTGGCCATCCTCTGGCATGAGATGTGGC
  363  ATGAAGGCCTGGAAGAGGCATCTCGTTTGTACTTTGGGGAAAGGAACGTGAAAGGCATGTTTGAGGTGCT
  364  GGAGCCCTTGCATGCTATGATGGAACGGGGCCCCCAGACTCTGAAGGAAACATCCTTTAATCAGGCCTAT
  365  GGTCGAGATTTAATGGAGGCCCAAGAGTGGTGCAGGAAGTACATGAAATCAGGGAATGTCAAGGACCTCA
  366  CCCAAGCCTGGGACCTCTATTATCATGTGTTCCGACGAATCTCAAAGCAGCTGCCTCAGCTCACATCCTT
  367  AGAGCTGCAATATGTTTCCCCAAAACTTCTGATGTGCCGGGACCTTGAATTGGCTGTGCCAGGAACATAT
  368  GACCCCAACCAGCCAATCATTCGCATTCAGTCCATAGCACCGTCTTTGCAAGTCATCACATCCAAGCAGA
  369  GGCCCCGGAAATTGACACTTATGGGCAGCAACGGACATGAGTTTGTTTTCCTTCTAAAAGGCCATGAAGA
  370  TCTGCGCCAGGATGAGCGTGTGATGCAGCTCTTCGGCCTGGTTAACACCCTTCTGGCCAATGACCCAACA
  371  TCTCTTCGGAAAAACCTCAGCATCCAGAGATACGCTGTCATCCCTTTATCGACCAACTCGGGCCTCATTG
  372  GCTGGGTTCCCCACTGTGACACACTGCACGCCCTCATCCGGGACTACAGGGAGAAGAAGAAGATCCTTCT
  373  CAACATCGAGCATCGCATCATGTTGCGGATGGCTCCGGACTATGACCACTTGACTCTGATGCAGAAGGTG
  374  GAGGTGTTTGAGCATGCCGTCAATAATACAGCTGGGGACGACCTGGCCAAGCTGCTGTGGCTGAAAAGCC
  375  CCAGCTCCGAGGTGTGGTTTGACCGAAGAACCAATTATACCCGTTCTTTAGCGGTCATGTCAATGGTTGG
  376  GTATATTTTAGGCCTGGGAGATAGACACCCATCCAACCTGATGCTGGACCGTCTGAGTGGGAAGATCCTG
  377  CACATTGACTTTGGGGACTGCTTTGAGGTTGCTATGACCCGAGAGAAGTTTCCAGAGAAGATTCCATTTA
  378  GACTAACAAGAATGTTGACCAATGCTATGGAGGTTACAGGCCTGGATGGCAACTACAGAATCACATGCCA
  379  CACAGTGATGGAGGTGCTGCGAGAGCACAAGGACAGTGTCATGGCCGTGCTGGAAGCCTTTGTCTATGAC
  380  CCCTTGCTGAACTGGAGGCTGATGGACACAAATACCAAAGGCAACAAGCGATCCCGAACGAGGACGGATT
  381  CCTACTCTGCTGGCCAGTCAGTCGAAATTTTGGACGGTGTGGAACTTGGAGAGCCAGCCCATAAGAAAAC
  382  GGGGACCACAGTGCCAGAATCTATTCATTCTTTCATTGGAGACGGTTTGGTGAAACCAGAGGCCCTAAAT
  383  AAGAAAGCTATCCAGATTATTAACAGGGTTCGAGATAAGCTCACTGGTCGGGACTTCTCTCATGATGACA
  384  CTTTGGATGTTCCAACGCAAGTTGAGCTGCTCATCAAACAAGCGACATCCCATGAAAACCTCTGCCAGTG
  385  CTATATTGGCTGGTGCCCTTTCTGGTAACTGGAGGCCCAGATGTGCCCATCACGTTTTTTCTGAGGCTTT
  386  TGTACTTTAGTAAATGCTTCCACTAAACTGAAACCATGGTGAGAAAGTTTGACTTTGTTAAATATTTTGA
  387  AATGTAAATGAAAAGAACTACTGTATATTAAAAGTTGGTTTGAACCAACTTTCTAGCTGCTGTTGAAGAA
  388  TATATTGTCAGAAACACAAGGCTTGATTTGGTTCCCAGGACAGTGAAACATAGTAATACCACGTAAATCA
  389  AGCCATTCATTTTGGGGAACAGAAGATCCATAACTTTAGAAATACGGGTTTTGACTTAACTCACAAGAGA
  390  ACTCATCATAAGTACTTGCTGATGGAAGAATGACCTAGTTGCTCCTCTCAACATGGGTACAGCAAACTCA
  391  GCACAGCCAAGAAGCCTCAGGTCGTGGAGAACATGGATTAGGATCCTAGACTGTAAAGACACAGAAGATG
  392  CTGACCTCACCCCTGCCACCTATCCCAAGACCTCACTGGTCTGTGGACAGCAGCAGAAATGTTTGCAAGA
  393  TAGGCCAAAATGAGTACAAAAGGTCTGTCTTCCATCAGACCCAGTGATGCTGCGACTCACACGCTTCAAT
  394  TCAAGACCTGACCGCTAGTAGGGAGGTTTATTCAGATCGCTGGCAGCCTCGGCTGAGCAGATGCACAGAG
  395  GGGATCACTGTGCAGTGGGACCACCCTCACTGGCCTTCTGCAGCAGGGTTCTGGGATGTTTTCAGTGGTC
  396  AAAATACTCTGTTTAGAGCAAGGGCTCAGAAAACAGAAATACTGTCATGGAGGTGCTGAACACAGGGAAG
  397  GTCTGGTACATATTGGAAATTATGAGCAGAACAAATACTCAACTAAATGCACAAAGTATAAAGTGTAGCC
  398  ATGTCTAGACACCATGTTGTATCAGAATAATTTTTGTGCCAATAAATGACATCAGAATTTTAAACATA
  399  obioma_chukueggu@cloudshell:~/Home/obioma$   grep -v '>' MTOR.fasta| wc-l
  400  -bash: wc-l: command not found
  401  obioma_chukueggu@cloudshell:~/Home/obioma$ 
  402  grep -v '>' MTOR.fasta| wc -l
  403  grep -v '>' MTOR.fasta | tr -dc 'A' | wc -c
  404  grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c
  405  grep -v '>' MTOR.fasta | tr -dc 'T' | wc -c
  406  sudo apt install bc
  407  echo "scale=2; ($(grep -v '>' MTOR.fasta |tr -dc 'G' | wc -c) + $(grep -v '>' MTOR.fasta | tr -dc 'C' | wc -c)) / $(grep -v '>' MTOR.fasta |tr -dc 'AGTC' | wc -c) * 100" | bc
  408  echo "Numbers of G:$(grep -o 'G' MTOR.fasta | wc -l)" >> obioma.fasta
  409  echo "Numbers of A:$(grep -o 'A' MTOR.fasta | wc -l)" >> obioma.fasta
  410  echo "Numbers of T:$(grep -o 'T' MTOR.fasta | wc -l)" >> obioma.fasta
  411  echo "Numbers of C:$(grep -o 'C' MTOR.fasta | wc -l)" >> obioma.fasta
  412  git push
  413  git clone https://github.com/Marvecodes/Francis-Collin
  414  git add .
  415  git commit -m save
  416  ls
  417  cd Francis-Collin
  418  ls
  419  cd ..
  420  mv obioma.fasta /Francis-Collin/
  421* cp obioma.fasta /Francis-Collin
  422  ls
  423  cd home
  424  cd Home
  425  ls
  426  cd..
  427  cd Francis-Collin
  428  cd ..
  429  ls
  430  cd obioma
  431  ls
  432  history
  433  echo history >> obioma.sh
  434  ls
  435  echo history
  436  nano
  437  history
  438  grep history >> obioma.sh
  439  ls
  440  cp obioma.sh > Francis-Collin
  441  cp obioma.sh ../Francis-Collin/
  442  cd ..
  443  ls
  444  cd output
  445  cd Francis-Collin
  446  ls
  447  mv obioma.sh /Script/
  448  cp obioms.sh /Script/
  449  cd Script
  450  cd ..
  451  mv obioma.sh /Script/
  452  cp obioma.sh /Script/
  453  git add .
  454  git commit -m codehistory
  455  git push
